"""update Tasks columm(complexity)

Revision ID: 3af19f4d3313
Revises: f0c63ad6ff90
Create Date: 2026-09-13 01:46:20.029750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af19f4d3313'
down_revision: Union[str, Sequence[str], None] = 'f0c63ad6ff90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
