"""add done pitch in Tasks models

Revision ID: f0c63ad6ff90
Revises: cc43666c8e70
Create Date: 2026-09-13 01:15:52.261057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c63ad6ff90'
down_revision: Union[str, Sequence[str], None] = 'cc43666c8e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'done')
    # ### end Alembic commands ###
